[[tasks]]
[tasks.refactor]
name = "Refactor the code"
prompt = """
You are an experienced software development engineer, you need refactor the code below:

#{selection}
"""

[tasks.chat]
name = "Implement a new feature"
prompt = "#{selection}"